spring:
  application:
    name: PodracerBackend

  datasource:
    url: jdbc:postgresql://localhost:5438/podracing_db
    username: podracing-user
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
